// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oop_s2_2_mvc_71757.Data;

#nullable disable

namespace oop_s2_2_mvc_71757.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosedDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 3,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 6,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 3,
                            ClosedDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 9,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 11,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 15,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 18,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 21,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 24,
                            Status = "Open"
                        },
                        new
                        {
                            Id = 9,
                            ClosedDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 3,
                            Status = "Closed"
                        },
                        new
                        {
                            Id = 10,
                            ClosedDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 6,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine inspection.",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 92
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor issues corrected.",
                            Outcome = "Pass",
                            PremisesId = 2,
                            Score = 78
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cooling logs missing.",
                            Outcome = "Fail",
                            PremisesId = 3,
                            Score = 55
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good hygiene practices.",
                            Outcome = "Pass",
                            PremisesId = 4,
                            Score = 88
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor storage adjustments.",
                            Outcome = "Pass",
                            PremisesId = 5,
                            Score = 67
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cross-contamination risk.",
                            Outcome = "Fail",
                            PremisesId = 6,
                            Score = 49
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Records up to date.",
                            Outcome = "Pass",
                            PremisesId = 7,
                            Score = 73
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent standards.",
                            Outcome = "Pass",
                            PremisesId = 8,
                            Score = 95
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cleaning schedule lapsed.",
                            Outcome = "Fail",
                            PremisesId = 9,
                            Score = 41
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine checks completed.",
                            Outcome = "Pass",
                            PremisesId = 10,
                            Score = 82
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Temperature control issues.",
                            Outcome = "Fail",
                            PremisesId = 11,
                            Score = 52
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good practice overall.",
                            Outcome = "Pass",
                            PremisesId = 12,
                            Score = 86
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Follow-up spot check.",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 90
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor labeling fixes.",
                            Outcome = "Pass",
                            PremisesId = 2,
                            Score = 63
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Handwashing signage missing.",
                            Outcome = "Fail",
                            PremisesId = 3,
                            Score = 58
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "No major concerns.",
                            Outcome = "Pass",
                            PremisesId = 4,
                            Score = 80
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Storage corrected.",
                            Outcome = "Pass",
                            PremisesId = 5,
                            Score = 76
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Staff training overdue.",
                            Outcome = "Fail",
                            PremisesId = 6,
                            Score = 44
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Satisfactory.",
                            Outcome = "Pass",
                            PremisesId = 7,
                            Score = 70
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent.",
                            Outcome = "Pass",
                            PremisesId = 8,
                            Score = 96
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Pest control documentation missing.",
                            Outcome = "Fail",
                            PremisesId = 9,
                            Score = 39
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good compliance.",
                            Outcome = "Pass",
                            PremisesId = 10,
                            Score = 85
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Improved controls.",
                            Outcome = "Pass",
                            PremisesId = 11,
                            Score = 61
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Equipment maintenance needed.",
                            Outcome = "Fail",
                            PremisesId = 12,
                            Score = 48
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine spot check.",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 77
                        });
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Ocean Rd",
                            Name = "Harbor Grill",
                            RiskRating = "Low",
                            Town = "Portstown"
                        },
                        new
                        {
                            Id = 2,
                            Address = "12 Maple St",
                            Name = "Maple Cafe",
                            RiskRating = "Medium",
                            Town = "Portstown"
                        },
                        new
                        {
                            Id = 3,
                            Address = "88 Dock Ave",
                            Name = "Night Market",
                            RiskRating = "High",
                            Town = "Portstown"
                        },
                        new
                        {
                            Id = 4,
                            Address = "7 Pine St",
                            Name = "Pine Diner",
                            RiskRating = "Medium",
                            Town = "Lakeside"
                        },
                        new
                        {
                            Id = 5,
                            Address = "21 Lake Rd",
                            Name = "Sunrise Bakery",
                            RiskRating = "Low",
                            Town = "Lakeside"
                        },
                        new
                        {
                            Id = 6,
                            Address = "9 River Walk",
                            Name = "River Sushi",
                            RiskRating = "High",
                            Town = "Lakeside"
                        },
                        new
                        {
                            Id = 7,
                            Address = "3 Summit Dr",
                            Name = "Hilltop BBQ",
                            RiskRating = "Medium",
                            Town = "Hillview"
                        },
                        new
                        {
                            Id = 8,
                            Address = "14 Garden Ln",
                            Name = "Garden Bistro",
                            RiskRating = "Low",
                            Town = "Hillview"
                        },
                        new
                        {
                            Id = 9,
                            Address = "101 Main St",
                            Name = "Central Pub",
                            RiskRating = "High",
                            Town = "Hillview"
                        },
                        new
                        {
                            Id = 10,
                            Address = "5 Orchard Rd",
                            Name = "Green Leaf",
                            RiskRating = "Low",
                            Town = "Portstown"
                        },
                        new
                        {
                            Id = 11,
                            Address = "66 Market St",
                            Name = "Spice Route",
                            RiskRating = "High",
                            Town = "Lakeside"
                        },
                        new
                        {
                            Id = 12,
                            Address = "2 Bay Blvd",
                            Name = "Coastal Eats",
                            RiskRating = "Medium",
                            Town = "Hillview"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.FollowUp", b =>
                {
                    b.HasOne("oop_s2_2_mvc_71757.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.Inspection", b =>
                {
                    b.HasOne("oop_s2_2_mvc_71757.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("oop_s2_2_mvc_71757.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
